services:
  - type: web
    name: crypto-bot-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py

  - type: worker
    name: crypto-bot-runner
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python auto_runner.py 